### ISSUE TITLE
Eating "Regeneration IV" Pickle retrieved from JEI crashes Game.

### ISSUE THREAD

**Issue by talonos2** [Icedice9/Complex-Crops#1]
Stack trace as follows:

```
java.lang.NullPointerException: Ticking player
	at net.minecraft.util.FoodStats.func_151686_a(SourceFile:32)
	at complexcrops.items.ItemPicklePotion.func_77654_b(ItemPicklePotion.java:71)
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:222)
	at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2779)
	at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1125)
	at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2678)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by mattcloward** [comment]
CNR
You must have some other mods that are causing the problem. First, I can't get a regen IV potion in JEI with the mods I have. When I do craft one though, it works just fine. Any ideas what mods would be causing this?
Thanks for the report!

**Comment by talonos2** [comment]
Upon closer inspection, the Regen IV potion in the JEI panel seems to be coming from the CoFH line. You could possibly try running it with CoFH core, Thermal Foundation, and Thermal Expansion.

**Comment by mattcloward** [comment]
Just tested it again with the mods you suggested and was able to obtain the pickle spoken of. It still didn’t crash for me, so it probably has something to do with a mod that tracks foods consumed. What mods are you using that do that?

**Comment by talonos2** [comment]
Ick.

Apple core, apple skin, hunger overhaul, spice of life, spice of life carrot edition. So... a bunch.

**Comment by mattcloward** [comment]
Alright! Found a fix! I'll probably put it out today.

**Comment by talonos2** [comment]
Could you commit it? I'm very curious.

**Comment by mattcloward** [comment]
Sure! The issue was really dumb. I copy pasted some code that I thought was doing one thing but really was setting the player to null and then trying to add stats to them. Oops... the fix will be in the ItemPicklePotion class.
